//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillStatus = new HashSet<BillStatus>();
            this.PayDetail = new HashSet<PayDetail>();
        }
    
        public int bill_id { get; set; }
        public Nullable<System.DateTime> bill_datecreated { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string bill_address { get; set; }
        public Nullable<int> bill_telephone { get; set; }
        public Nullable<decimal> bill_sum { get; set; }
        public Nullable<System.DateTime> bill_dateset { get; set; }
        public Nullable<bool> bill_status { get; set; }
        public string bill_note { get; set; }
    
        public virtual Seller Seller { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillStatus> BillStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayDetail> PayDetail { get; set; }
    }
}
