//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillStatus
    {
        public int status_id { get; set; }
        public string status_name { get; set; }
        public Nullable<int> bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
