//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collection()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int collection_id { get; set; }
        public string collection_name { get; set; }
        public string collection_image1 { get; set; }
        public string collection_image2 { get; set; }
        public string collection_image3 { get; set; }
        public Nullable<System.DateTime> collection_datecreate { get; set; }
        public Nullable<bool> collection_active { get; set; }
        public Nullable<bool> collection_bin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
