//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int fa_id { get; set; }
        public Nullable<System.DateTime> fa_datereated { get; set; }
        public Nullable<bool> fa_bin { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
