//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSMall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GSMall()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int gsmall_id { get; set; }
        public string gsmall_name { get; set; }
        public string gsmall_slogan { get; set; }
        public Nullable<bool> gsmall_active { get; set; }
        public Nullable<System.DateTime> gsmall_datecreate { get; set; }
        public string gsmall_bg { get; set; }
        public string gsmall_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
