//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDetail
    {
        public int pay_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> pay_money { get; set; }
        public Nullable<int> pay_amount { get; set; }
        public Nullable<System.DateTime> pay_datecreated { get; set; }
        public Nullable<int> bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
