//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Category
    {
        public int pc_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> csc_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ClassificationSubCategory ClassificationSubCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
