//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Product = new HashSet<Product>();
            this.ReplyComment = new HashSet<ReplyComment>();
        }
    
        public int seller_id { get; set; }
        public string seller_pass { get; set; }
        public string seller_email { get; set; }
        public string seller_telephone { get; set; }
        public string seller_token { get; set; }
        public string seller_slider1 { get; set; }
        public string seller_slider2 { get; set; }
        public string seller_slider3 { get; set; }
        public string seller_link1 { get; set; }
        public string seller_link2 { get; set; }
        public string seller_link3 { get; set; }
        public string seller_logo { get; set; }
        public Nullable<bool> seller_active { get; set; }
        public string seller_nameshop { get; set; }
        public Nullable<System.DateTime> seller_datecreated { get; set; }
        public string seller_address { get; set; }
        public Nullable<System.DateTime> seller_datelogin { get; set; }
        public string seller_detail { get; set; }
        public string seller_description { get; set; }
        public Nullable<int> seller_role { get; set; }
        public string seller_nicename { get; set; }
        public string seller_provincecity { get; set; }
        public string seller_district { get; set; }
        public Nullable<bool> seller_bin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyComment> ReplyComment { get; set; }
    }
}
