//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_GSshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategory()
        {
            this.ClassificationSubCategory = new HashSet<ClassificationSubCategory>();
            this.Product = new HashSet<Product>();
        }
    
        public int subcategory_id { get; set; }
        public string subcategory_name { get; set; }
        public string subcategory_image { get; set; }
        public Nullable<System.DateTime> subcategory_datecreated { get; set; }
        public Nullable<bool> subcategory_active { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<bool> subcategory_level { get; set; }
        public Nullable<bool> subcategory_bin { get; set; }
        public Nullable<int> subcategory_view { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassificationSubCategory> ClassificationSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
